### PR TITLE
Fix Respect `output.publicPath`

### PR DESCRIPTION
**Pull request by bekos**

### CODE REVIEW

**Comment by bekos** [comment]
@addyosmani What's your opinion on this? This is actually blocking us from using it in production with CDN.

**Comment by addyosmani** [comment]
This was something I had originally wanted to implement but wasn't sure how much folks would want it. Landed in master. I'll get a release cut shortly.

**Comment by addyosmani** [comment]
This is now in 1.2.0 on npm.

**Comment by bekos** [comment]
Great! Thx 👍

**Pull request merged**
