### PR TITLE
Add ability to `exclude` named chunks

### PR DESCRIPTION
**Pull request by bekos**
First commit is just a refactor, so it's easier to review.

### CODE REVIEW

**Comment by jantimon** [comment]
This won't work well with multiple html-webpack-plugin instances - maybe you could take some ideas from here:

https://github.com/jantimon/resource-hints-webpack-plugin

**Comment by bekos** [comment]
@jantimon I suppose you speak about plugin's API in general, and not just this `exclude` feature, right?
If that's true you should probably raise another issue to discuss how the API can be extended/altered based on the fact that there could be multiple html-webpack-plugin instances.

**Comment by jantimon** [comment]
Well the preload-webpack-plugin is basically a rewrite of the resource-hints-webpack-plugin with additional async support. 
Moved it to #13 
Would also be happy if you could add a pr to resource-hints-webpack-plugin to support async chunks :)

**Comment by bekos** [comment]
Closing as this is covered by `fileBlacklist` option.

**Pull request closed without merging**
